### ISSUE TITLE
Class Loading Issue with PL/Java

### ISSUE THREAD

**Issue by JanaParthasarathy** [tada/pljava#361]
I am having 2 issues when I run my java encryption service on Postgres PL/Java.

_Issue 1_: **java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder**
It happens when I call encryption service first and/ second time but subsequent request is successful , still even with success request  I can see ClassNotFoundException in the log trace.
It only break in first and /second request.

 _Issue 1_:java.lang.NoClassDefFoundError:Key
This happens randomly when I try to deserialize using jackson ObjectMapper
key = objectMapper.readValue(jsonKey, Key.class);
But once this issue happens , all request to encryption service fails with same NoClassDefFoundError:Key.
I have kill psql process and restart it to make it work.

I am using Java 11 and PL/Java 1.5.6

Please let me know if you have any suggestions or solutions for this issue ?

Thank for your support.

**Comment by jcflack** [comment]
Hi,

Can you include the output of:

```sql
SELECT schemaname, jarname
  FROM sqlj.classpath_entry NATURAL JOIN sqlj.jar_repository
  ORDER BY schemaname, ordinal;

SHOW pljava.classpath;
```

Is there something in your requirements that keeps you on a 1.5 PL/Java rather than a 1.6?

Can you include log output from a session that shows the problem, where

```sql
SET log_min_messages TO debug2;
```

was done before the first use of PL/Java in a new session?

**Comment by JanaParthasarathy** [comment]
Hi,

I have included the output of the queries below and also I have set log_min_messages TO debug5;

```
SELECT schemaname, jarname
  FROM sqlj.classpath_entry NATURAL JOIN sqlj.jar_repository
  ORDER BY schemaname, ordinal;


schemaname |     jarname      
------------+------------------
 public     | "JarName"
(1 row)

```

```
SHOW pljava.classpath;

 `/usr/pgsql-12/share/pljava/pljava-1.5.6.jar`
```
I was not finding 1.6.2 PL/Java for Postgress12 - Redhat Linux box.
So building 1.6.2 PL/Java and installing manually,will it help?

Thank you

**Comment by jcflack** [comment]
To be honest, I don't know whether 1.6.2 will help with your issue ... I don't know what's causing the issue yet. But PL/Java 1.5,x is getting minimal maintenance at present.

It's unfortunate that 1.6.2 isn't prebuilt for your environment. You might try building it from source, but I am expecting to do a 1.6.3 shortly (to include PG 14 support), so perhaps rather than going to the effort of building 1.6.2 from source, it would be more efficient to wait for 1.6.3.

Can you include any of the log information generated from your failure with the `log_min_messages` setting?

**Comment by JanaParthasarathy** [comment]
i ,

Thanks for looking into this issue.

In Postgres, We have Encryption UDF(Java function) which call backend service to get Secret key.
Sometimes it works fine and we are able to get encrypted text but randomly we are getting these ClassNotFoundException and NoClassDefFoundError

I have pasted part of log here and also attached complete logs for both these issue and also for successful request.
```
DEBUG:  23 Sep 21 10:48:53 sun.net.www.protocol.http.HttpURLConnection sun.net.www.MessageHeader@49c6ee4a13 pairs: {null: HTTP/1.1 200 OK}{Access-Control-Max-Age: 36000}{Access-Control-Allow-Methods: GET,PUT,POST,DELETE,OPTIONS}{Access-Control-Allow-Origin: *}{Cache-Control: no-cache}{Strict-Transport-Security: max-age=31536000; includeSubDomains}{service-transaction-id: 7492d45c-4078-1016-739c-2b78444bcb17}
DEBUG:  23 Sep 21 10:48:53 javax.ws.rs.client.FactoryFinder Unable to load provider class org.glassfish.jersey.client.JerseyClientBuilder using custom classloader jdk.internal.loader.ClassLoaders$AppClassLoader trying again with current classloader.

java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at javax.ws.rs.client.FactoryFinder.newInstance(FactoryFinder.java:79)
	at javax.ws.rs.client.FactoryFinder.find(FactoryFinder.java:185)
	at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:67)
	at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:94)
	at com.XXXXXX.yyy.kmes.kms.KmsClient.getAccessToken(KmsClient.java:234)
	at com.XXXXXX.yyy.kmes.kms.KmsClient.buildPopTokenForCreateKeyRequest(KmsClient.java:208)
	at com.XXXXXX.yyy.kmes.kms.KmsClient.getKeyFromKmes(KmsClient.java:141)
	at com.XXXXXX.yyy.kmes.kms.KmsClient.getActiveKeyByName(KmsClient.java:87)
	at com.XXXXXX.yyy.kmes.kms.KeyManager.findActiveKeyByName(KeyManager.java:51)
	at com.XXXXXX.yyy.kmes.crypto.Cipher.encryptU(Cipher.java:143)
	at com.XXXXXX.yyy.kmes.crypto.Ekmes.encryptU(Ekmes.java:72)
	at com.XXXXXX.yyy.postgres.EkmesEncrypt.ekmesEncrypt(EkmesEncrypt.java:36)
```






And also the jar we have installed has all the dependency in it, i verified by running following cmd,

```
SELECT entryid, entryname FROM sqlj.jar_entry where entryname LIKE '%org/glassfish/jersey/client%';
1658389 | org/glassfish/jersey/client/InvocationInterceptorStages.class
1658390 | org/glassfish/jersey/client/JerseyClient$1.class
1658391 | org/glassfish/jersey/client/JerseyClient$2.class
1658392 | org/glassfish/jersey/client/JerseyClient$ShutdownHook.class
1658393 | org/glassfish/jersey/client/JerseyClient.class
1658394 | org/glassfish/jersey/client/JerseyClientBuilder$1.class
1658395 | org/glassfish/jersey/client/JerseyClientBuilder.class
1658396 | org/glassfish/jersey/client/JerseyCompletionStageRxInvoker.class
1658397 | org/glassfish/jersey/client/JerseyInvocation$1.class
1658398 | org/glassfish/jersey/client/JerseyInvocation$2.class
1658399 | org/glassfish/jersey/client/JerseyInvocation$AsyncInvoker.class
1658400 | org/glassfish/jersey/client/JerseyInvocation$Builder.class
1658401 | org/glassfish/jersey/client/JerseyInvocation$EntityPresence.class
1658402 | org/glassfish/jersey/client/JerseyInvocation$InvocationResponseCallback.class
1658403 | org/glassfish/jersey/client/JerseyInvocation.class
1658404 | org/glassfish/jersey/client/JerseyWebTarget.class
1658405 | org/glassfish/jersey/client/RequestEntityProcessing.class
1658406 | org/glassfish/jersey/client/RequestProcessingInitializationS
```

```
# SELECT version();

------------------------------------------------------------------------------------------------------------
 PostgreSQL 12.7 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1), 64-bit
(1 row)

```

```
# SHOW server_encoding;

 server_encoding
-----------------
 UTF8
(1 row)

```
Thanks again !!

**Comment by jcflack** [comment]
There seem to be a few things going on here.

First, it is not always the same class loader failing to load a class; but I think the circumstances are different.

I see some instances like this, where PL/Java's own class loader fails to load an OSGi class:

```
java.lang.ClassNotFoundException: org.osgi.framework.BundleReference
        at org.postgresql.pljava.sqlj.Loader.findClass(Loader.java:404)
```
I think that one may be harmless, because it is followed by a line like this:

```
org.glassfish.jersey.internal.ServiceFinder Running in a non-OSGi environment
```
so it seems to mean that `org.osgi.framework.BundleReference` is allowed to be missing, and Jersey will simply proceed without OSGi.

The others you are noticing do not involve the PL/Java class loader:

```
java.lang.ClassNotFoundException: org.glassfish.jersey.internal.RuntimeDelegateImpl
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at javax.ws.rs.client.FactoryFinder.newInstance(FactoryFinder.java:79)
        at javax.ws.rs.client.FactoryFinder.find(FactoryFinder.java:185)
```
Because these classes are contained in the jar installed in the database with `sqlj.install_jar`, Java's stock `AppClassLoader` or `BuiltinClassLoader` will not be able to find them; the lookups should be done using PL/Java's loader.

It appears that the `FactoryFinder` [is calling][ffcall] the flavor of `Class.forName` that takes an explicit `ClassLoader` argument. And it is being called by the [`find`][fffind] method, which uses the current Java thread's `getContextClassLoader` to find the right loader to use.

PL/Java has not, historically, set the context class loader when it enters a function. For a good while now, I have been thinking that was a mistake, and it ought to do so, but I have been reluctant to change the longstanding behavior. Until it changes in PL/Java, you can just set it manually in your PL/Java entry methods:

```java
... ekmesEncrypt(...) {
  Thread.currentThread().setContextClassLoader(EkmesEncrypt.class.getClassLoader());
  ...
}
```
That's one thing.

You also have activity on multiple threads. Java is multithreaded but PostgreSQL isn't, so there can be difficulties here. You may want to read about the `java_thread_pg_entry` setting on the [configuration variables][cvbls] page.

I can tell the setting is currently `allow`, because of entries in the logs like this

```
DEBUG:  Set stack base for thread 94772808854344
DEBUG:  Restored stack base for thread 94772807871304
```
which indicate that entry into PostgreSQL isn't always happening from the same Java thread. PL/Java makes sure not to allow more than one thread into PostgreSQL _at a time_, but historically (i.e., when `allow` is the setting) will allow one in and then another. That can still lead to surprise in some cases, such as here:

```
DEBUG:  An attempt was made to call a PostgreSQL backend function after an elog(ERROR) had been issued
```
which might indicate that one thread had been in PostgreSQL and logged something at the `ERROR` level and returned to Java in the process of handling it, while a second thread then entered PostgreSQL before the first thread reached a recovered state.

One possible cause is use of finalizers in the application or in a library. Java's garbage collector can discover objects are unreachable at pretty much any odd time, and if anything their finalizers do involves interacting with PostgreSQL, that can happen at unpredictable times. `Object.finalize` has been deprecated officially since Java 9. PL/Java itself no longer uses it (which is why PL/Java itself can now pass its test suite with `java_thread_pg_entry` set to `block`), but there is still code in the wild that uses finalizers.

It might be necessary to design the application code to be more explicit about serializing its own accesses into PostgreSQL. Keep in mind that even attempts to load classes, if they are in `sqlj.install_jar` jars, involve access to PostgreSQL, whenever they happen on whatever thread, and so can things like type OID lookups that happen under the hood in JDBC methods.

A design that tries to confine those things onto one thread, or even just has a single thread eagerly load a list of classes in advance, might prove helpful.

[ffcall]: https://github.com/eclipse-ee4j/jaxrs-api/blob/67acde2d5155ecb5cf957c96f7ad446b9fc1b54c/jaxrs-api/src/main/java/javax/ws/rs/client/FactoryFinder.java#L79
[fffind]: https://github.com/eclipse-ee4j/jaxrs-api/blob/67acde2d5155ecb5cf957c96f7ad446b9fc1b54c/jaxrs-api/src/main/java/javax/ws/rs/client/FactoryFinder.java#L119
[cvbls]: https://tada.github.io/pljava/use/variables.html

**Comment by jcflack** [comment]
Has my comment on this issue from last Thursday been helpful?

I am considering including a change in 1.6.3 to set the context class loader to be that _initiating loader_ from which PL/Java loaded the class of the function being executed, as a bug fix in response to (part of) this issue. As I mentioned, I had considered it in the past but had not implemented it, on general behavior stability grounds.

On further thought, the behavior stability concern seems minor. If there is existing code that has needed the context loader to be set, it probably already is doing so, and won't be affected by whether PL/Java has set the value first. And in some cases (not yours, as your schema classpath is only one element long), for a schema classpath longer than one element, `getClassLoader` on the function's own class (which returns the _defining loader_) won't necessarily return the right thing. Therefore it seems that PL/Java has the information that's needed, and should have responsibility to set the context loader. Then your `FactoryFinder` loads ought to succeed without extra work on your part (as long as they happen on the same thread).

There is already [a notion][pstm], used in PL/Java internally, of the loader or type map "for the schema in which the innermost executing PL/Java function on the call stack is declared", which means the same thing as PL/Java's _initiating loader_ for the function's class, so it would be natural for the thread's context loader to be the same.

[pstm]: https://tada.github.io/pljava/develop/coercion.html#The_per-schema_type_map

**Comment by JanaParthasarathy** [comment]
Hi,

Sorry for my late response. Thanks for your inputs. Based on your suggestions I was able to resolve some of the issues but not completely. I blocked multi thread access to Postgres by setting java_thread_pg_entry to block.
And also set Context Class Loader in my function, but it slowed down the process
We were doing some other changes by using different javax.rs implementation (from Jersey to RestEasy) to see the difference. I will keep you posted on our findings.

Could you please confirm if the current version (1.6.2) of the library is GA / publicly available for use ? 

Thanks again for your support!

**Comment by jcflack** [comment]
Yes, 1.6.2 [was released about ten months ago][v162].

I am working at the moment on 1.6.3, which should be ready fairly soon. It will include some bug fixes from 1.6.2, so if you are not using 1.6.2 already, there is not long to wait for 1.6.3.

Setting `java_thread_pg_entry` to `block` will certainly prevent other threads in an application from entering postgres, but it doesn't really fix anything if that is what the application is doing. The other threads will simply block forever, and could lead to deadlock for the application as a whole. You can use a JMX client, like `jconsole` or `visualvm` or `jhsdb` to see what threads are being blocked in what pieces of code.

Or, you can set `java_thread_pg_entry` to `throw` or to `error` and there will be exceptions when other threads try to enter PostgreSQL, and that way you can easily see where the problems are. If the code can be rearranged so that it runs under `throw` or `error` and no such exceptions are thrown anymore, then you can change the setting to `block`, and the application should run with no threads getting blocked.

[v162]: https://github.com/tada/pljava/releases/tag/V1_6_2

**Comment by jcflack** [comment]
In your case, you have only one `sqlj` class path set, so only one loader for any of your function calls. That's a case easy to optimize for. On the other side, there's a slight extra overhead in the `java_thread_pg_entry=allow` case that has to be added to quiet `-Xcheck:jni` warnings (even though they are for a condition that Should Never Happen). At the end of all that, the total extra cost per call seems to be about:

```
java_thread_pg_entry == allow:
      1.6 µs per call, when every call requires setting
      0.7 µs per call, when consecutive calls use same loader
    
java_thread_pg_entry != allow:
      0.7 µs per call, when every call requires setting
      0.2 µs per call, when consecutive calls use same loader
```
(tested on a Xeon X5650, relative to 7a7f394.)

I think that's about as good as I'm likely to get it, and will make that a pull request into 1.6.3.
